server:
  port: 8088
  servlet:
    context-path: /
spring:
  datasource:
    username: root
    password: 2039
    url: jdbc:mysql://localhost:3306/depository?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    elasticsearch:
      repositories:
        enabled: true
      #cluster-nodes: 127.0.0.1:9300

